[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "dark"              # or "light"
primaryColor = "#F63366"
backgroundColor = "#262730"
secondaryBackgroundColor = "#383B40"
textColor = "#FAFAFA"
font = "sans serif"

[global]
# Optional: hide the hamburger menu and footer
hideStreamlitLogo = false